CREATE DATABASE gerenciamentoDoacoes;
USE gerenciamentoDoacoes;

CREATE TABLE doador (
RG VARCHAR(9) UNIQUE NOT NULL PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
telefone VARCHAR (18) NOT NULL,
email VARCHAR (50) NOT NULL
);

CREATE TABLE doação ( 
id_doacao INT AUTO_INCREMENT PRIMARY KEY,
cnpj VARCHAR(19) NOT NULL,
RG VARCHAR(9) UNIQUE NOT NULL,
cnpj_beneficiario VARCHAR(19) NOT NULL,
descricao VARCHAR(100) NOT NULL,
categoria VARCHAR(50) NOT NULL,
FOREIGN KEY (CNPJ) REFERENCES instituição(CNPJ),
FOREIGN KEY (RG) REFERENCES doador(RG)
);

CREATE TABLE instituição (
cnpj VARCHAR(18) NOT NULL PRIMARY KEY,
nome VARCHAR(255) NOT NULL
);

CREATE TABLE rastreio (
id_rastreio INT AUTO_INCREMENT PRIMARY KEY,
id_doacao INT,
status VARCHAR(50) NOT NULL,
FOREIGN KEY (id_doacao) REFERENCES doação(id_doacao)
);

CREATE TABLE instituição_beneficiada (
CNPJ_beneficiario VARCHAR(19) NOT NULL PRIMARY KEY,
nome VARCHAR (255) NOT NULL,
endereco VARCHAR (200) NOT NULL,
email VARCHAR (50) NOT NULL,
telefone VARCHAR(18) NOT NULL
);




